-- AlterTable
ALTER TABLE "posts" ALTER COLUMN "title" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "place" SET DATA TYPE VARCHAR(250),
ALTER COLUMN "public_id" SET DATA TYPE VARCHAR(14);

-- AlterTable
ALTER TABLE "uploads" ALTER COLUMN "file_type" SET DATA TYPE VARCHAR(10);

-- AlterTable
ALTER TABLE "user_sessions" ALTER COLUMN "sid" SET DATA TYPE VARCHAR(48);
